/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.cidadao;

import coletainteligente.Cidadao;
import coletainteligente.Descarte;
import coletainteligente.Lixeira;
import coletainteligentedao.DescarteDAO;
import coletainteligentedao.LixeiraDAO;
import java.util.Calendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thiag
 */
public class TelaCadastroDescarte extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalCidadao
     */
    private Lixeira lixeira;
   
    
    public TelaCadastroDescarte() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLatitude = new javax.swing.JTextField();
        jTextFieldLongitude = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonLocalizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldDistancia = new javax.swing.JTextField();
        jTextFieldDirecao = new javax.swing.JTextField();
        jButtonMapa = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTFcodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCodCidadao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cidadão");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setText("Lixeira inteligente vazia mais próxima");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jTextFieldLatitude.setEditable(false);
        jTextFieldLatitude.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldLatitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 95, -1));

        jTextFieldLongitude.setEditable(false);
        jTextFieldLongitude.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldLongitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 95, -1));

        jLabelCodigo.setText("Código");
        getContentPane().add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel4.setText("Longitude");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jButton1.setText("Cadastar Descarte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jTextFieldDistancia.setEditable(false);
        jTextFieldDistancia.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 96, -1));

        jTextFieldDirecao.setEditable(false);
        jTextFieldDirecao.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldDirecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 90, -1));

        jButtonMapa.setText("Visualizar no Mapa");
        jButtonMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jTFcodigo.setEditable(false);
        jTFcodigo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTFcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 95, -1));

        jLabel5.setText("Latitude");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jTextFieldCodCidadao.setEditable(false);
        getContentPane().add(jTextFieldCodCidadao, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 40, -1));

        jLabel3.setText("Codigo Cidadão");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        setSize(new java.awt.Dimension(490, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
        // TODO add your handling code here:
        //ESTA PARTE NÃO ESTÁ ACRESCENTANDO NADA AO SISTEMA POR ENQUANTO
        //DEVERIA BUSCAR A LOCALIZAÇÃO DE UMA LIXEIRA NO ARQUIVO, MAS TÔ COM PREGUIÇA
       Random random = new Random();
        int direcao;
        
        LixeiraDAO lixeiradao = new LixeiraDAO();
        
        lixeira = lixeiradao.lixeiraVazia();
        
        if (lixeira.getCodigo() != 0){
            
            jTextFieldLatitude.setText(Float.toString(lixeira.getLatitude()));
            jTextFieldLongitude.setText(Float.toString(lixeira.getLongitude()));
            jTFcodigo.setText(Integer.toString(lixeira.getCodigo()));
            jTextFieldDistancia.setText(String.valueOf(random.nextInt(10)) + " Minutos");

            direcao = random.nextInt(2);

            if(direcao == 0)
            {
                jTextFieldDirecao.setText("Go Right");
            }else
            {
                jTextFieldDirecao.setText("Go Left");
            }
        }else{
        
            JOptionPane.showMessageDialog(null, "Não há lixeira disponível para realizar descarte!");
        }
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //MAIS UMA VEZ ERA PRA ESTAR BUSCANDO AS INFORMAÇÕES DO ARQUIVO OU BD, MAS A PREGUIÇA FEZ ASSIM
        
        if (lixeira.getCodigo() != 0){
            
            Calendar data = Calendar.getInstance();

            try {
                lixeira.setNivelAtual(Float.toString((100 - lixeira.getNivelAtual())/3));
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastroDescarte.class.getName()).log(Level.SEVERE, null, ex);
            }

            Cidadao cidadao = new Cidadao();
            
            try {
                cidadao.setCodigo(jTextFieldCodCidadao.getText());
            } catch (Exception ex) {
                Logger.getLogger(TelaCadastroDescarte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Descarte descarte = new Descarte();
            descarte.setCidadao(cidadao);
            descarte.setLixeira(lixeira);
            descarte.setData(data.getTime());
            descarte.setVolume(Float.toString((lixeira.getCapacidade() * lixeira.getNivelAtual())/100));

            DescarteDAO descartedao = new DescarteDAO();
            descartedao.insere(descarte);

           // PersistenciaArquivo registro = new PersistenciaArquivo();
            //registro.salvaDescarte(descarte);

            JOptionPane.showMessageDialog(null, "Descarte Registrado");
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapaActionPerformed
        // TODO add your handling code here:
        TelaMapa tMapa = new TelaMapa();
        tMapa.show(true);
    }//GEN-LAST:event_jButtonMapaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDescarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDescarte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonMapa;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCodigo;
    public static javax.swing.JTextField jTFcodigo;
    public static javax.swing.JTextField jTextFieldCodCidadao;
    private javax.swing.JTextField jTextFieldDirecao;
    private javax.swing.JTextField jTextFieldDistancia;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    // End of variables declaration//GEN-END:variables
}
