/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import coletainteligente.Bairro;
import coletainteligente.Lixeira;
import coletainteligentedao.BairroDAO;
import coletainteligentedao.LixeiraDAO;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import validador.ValidadorLixeira;

/**
 *
 * @author Vinicius
 */
public class TelaCadastroLixeira extends javax.swing.JFrame {

  
    //CRIA TABELA
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form TelaCadastroLixeira
     */
    public TelaCadastroLixeira() {
        initComponents();
        inicializa();
    }

    private void inicializa() {
       
        //CRIA CABEÇALHO
        model.setColumnIdentifiers(new Object[]{"Lixeira", "Bairro","Capacidade", "Latitude", "Longitude", "Nível Atual"});
        //SETANDO TABELA
        jTableLixeira.setModel(model);
        //AUMENTA O TAMANHO DA SEGUNDA COLUNA
        jTableLixeira.getColumnModel().getColumn(1).setPreferredWidth(190);
        listaLixeiras();
        
        
        BairroDAO bairroDAO = new BairroDAO();
        ArrayList listaBairro = bairroDAO.selectListaBairro();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Todos");
        jComboBoxBairro.removeAllItems();
        for (Object bairro : listaBairro) {
            jComboBox1.addItem((String) bairro);
            jComboBoxBairro.addItem((String) bairro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conexaoDB1 = new conexao.ConexaoDB();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCapacidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLatitude = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLongitude = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLixeira = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigoLixeira = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNivelAtual = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Lixeiras");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Bairro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jTextFieldCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCapacidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 260, 70, -1));

        jLabel1.setText("Capacidade");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jComboBoxBairro.setSelectedItem(this);
        jComboBoxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 190, 20));

        jLabel5.setText("Latitude");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 60, -1));
        getContentPane().add(jTextFieldLatitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 86, -1));

        jLabel6.setText("Longitude");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 60, -1));
        getContentPane().add(jTextFieldLongitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 86, -1));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 126, -1));

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 89, -1));

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jTableLixeira.setAutoCreateRowSorter(true);
        jTableLixeira.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLixeira.setDropMode(javax.swing.DropMode.ON);
        jTableLixeira.getTableHeader().setReorderingAllowed(false);
        jTableLixeira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLixeiraMouseClicked(evt);
            }
        });
        jTableLixeira.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableLixeiraKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLixeira);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 570, 170));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 86, -1));

        jLabel4.setText("Filtrar por Bairro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel7.setText("Código");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 61, -1));

        jTextFieldCodigoLixeira.setEnabled(false);
        jTextFieldCodigoLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoLixeiraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigoLixeira, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, -1));

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel2.setText("Nível_Atual");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jTextFieldNivelAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNivelAtualActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNivelAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 56, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 206, -1));

        setSize(new java.awt.Dimension(643, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCapacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCapacidadeActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Lixeira lixeira = new Lixeira();
        Bairro bairro = new Bairro();
        String capacidade = jTextFieldCapacidade.getText();
        String latitude = jTextFieldLatitude.getText();
        String longitude = jTextFieldLongitude.getText();
        String nivelAtual = jTextFieldNivelAtual.getText();
        BairroDAO bairrodao = new BairroDAO();
        String nomeBairro = jComboBoxBairro.getSelectedItem().toString();
        String codbairro = Integer.toString(bairrodao.codBairro(nomeBairro));
        try {
            lixeira.setRegiao(bairro);
            lixeira.bairro.setCodigo(codbairro);
            lixeira.setCapacidade(capacidade);
            lixeira.setLatitude(latitude);
            lixeira.setLongitude(longitude);
            lixeira.setNivelAtual(nivelAtual);
            
            LixeiraDAO lixeiradao = new LixeiraDAO();
            lixeiradao.insere(lixeira);
            listaLixeiras();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroLixeira.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Campos obrigatórios não estão preenchidos");
        }
        //System.out.println(capacidade + latitude + longitude + bairro);

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jComboBoxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBairroActionPerformed
        System.out.println("linha" + jTableLixeira.getSelectionModel());
    }//GEN-LAST:event_jComboBoxBairroActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldLatitude.setText("");
        jTextFieldLongitude.setText("");
        jTextFieldCapacidade.setText("");
        jTextFieldCodigoLixeira.setText("");
        jTextFieldNivelAtual.setText(""); 
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String instrucaoDel = "DELETE FROM lixeira WHERE cod_lixeira = ?";
        if (!jTextFieldCodigoLixeira.getText().equalsIgnoreCase("")){
            LixeiraDAO lixeiradao = new LixeiraDAO();
            instrucaoDel = instrucaoDel.replace("?", jTextFieldCodigoLixeira.getText());
            lixeiradao.genericSQL(instrucaoDel);
            listaLixeiras();
        }
        else {
            JOptionPane.showMessageDialog(null, "Só é possivel excluir lixeiras já cadastradas");
        }
     
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableLixeiraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLixeiraKeyReleased
        
    }//GEN-LAST:event_jTableLixeiraKeyReleased

    private void jTextFieldCodigoLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoLixeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoLixeiraActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        Lixeira lixeira = new Lixeira();
        Bairro bairro = new Bairro();
        BairroDAO bairrodao = new BairroDAO();
        
        String codLixeira = jTextFieldCodigoLixeira.getText();
        String nomeBairro = jComboBoxBairro.getSelectedItem().toString();
        String codbairro = Integer.toString(bairrodao.codBairro(nomeBairro));
        String capacidade = jTextFieldCapacidade.getText();
        String latitude = jTextFieldLatitude.getText();
        String longitude = jTextFieldLongitude.getText();
        String nivelAtual = jTextFieldNivelAtual.getText();
        
        try {
            lixeira.setCodigo(codLixeira);
            lixeira.setRegiao(bairro);
            lixeira.bairro.setCodigo(codbairro);
            lixeira.setCapacidade(capacidade);
            lixeira.setLatitude(latitude);
            lixeira.setLongitude(longitude);
            lixeira.setNivelAtual(nivelAtual);
            
            LixeiraDAO lixeiradao = new LixeiraDAO();
            lixeiradao.setLixeira(lixeira);
            listaLixeiras();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(TelaCadastroLixeira.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTableLixeiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLixeiraMouseClicked
        selecionaLinha();
    }//GEN-LAST:event_jTableLixeiraMouseClicked

    private void jTextFieldNivelAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNivelAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNivelAtualActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Todos")){

            listaLixeiras();  

       }else {

            filtraLixeirasPorBairro();
   }
    
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public void listaLixeiras() {
        
        // REMOVE LINHA DAS TABELAS
        while (model.getRowCount() > 0)
        {
         model.removeRow(0);
        }
          
        LixeiraDAO lixeiradao = new LixeiraDAO();
        lixeiradao.listaLixeiras(model);    
        jTableLixeira.setModel(model);
        jScrollPane1.setViewportView(jTableLixeira); 
       
    }
    
    public void filtraLixeirasPorBairro() {
       
        // REMOVE LINHA DAS TABELAS
        while (model.getRowCount() > 0)
        {
         model.removeRow(0);
        }
        
        LixeiraDAO lixeiradao = new LixeiraDAO();
        BairroDAO bairrodao = new BairroDAO();
        String nomeBairro = jComboBox1.getSelectedItem().toString();
        String codbairro = Integer.toString(bairrodao.codBairro(nomeBairro));
        lixeiradao.filtraLixeirasPorBairro(model, codbairro);    
        jTableLixeira.setModel(model);
        jScrollPane1.setViewportView(jTableLixeira); 

    }
    
    public void selecionaLinha() {
        
        int select = jTableLixeira.getSelectedRow();
        jTextFieldCodigoLixeira.setText(jTableLixeira.getModel().getValueAt(select,0).toString());
        jComboBoxBairro.setSelectedItem(jTableLixeira.getModel().getValueAt(select,1).toString());
        jTextFieldCapacidade.setText(jTableLixeira.getModel().getValueAt(select,2).toString());
        jTextFieldLatitude.setText(jTableLixeira.getModel().getValueAt(select,3).toString());
        jTextFieldLongitude.setText(jTableLixeira.getModel().getValueAt(select,4).toString());
        jTextFieldNivelAtual.setText(jTableLixeira.getModel().getValueAt(select,5).toString());
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLixeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLixeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLixeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLixeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLixeira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private conexao.ConexaoDB conexaoDB1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxBairro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLixeira;
    private javax.swing.JTextField jTextFieldCapacidade;
    private javax.swing.JTextField jTextFieldCodigoLixeira;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    private javax.swing.JTextField jTextFieldNivelAtual;
    // End of variables declaration//GEN-END:variables
}
