/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author thiag
 */
public class TelaPrincipalAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalAdm
     */
    public TelaPrincipalAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonLixeira = new javax.swing.JButton();
        jButtonColetor = new javax.swing.JButton();
        cadastraBairro = new javax.swing.JButton();
        jButtonSituacaoOperacional = new javax.swing.JButton();
        jButtonColeta = new javax.swing.JButton();
        jButtonStatus = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Administrador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jButtonLixeira.setText("Cadastrar Lixeira");
        jButtonLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLixeiraActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLixeira, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, -1));

        jButtonColetor.setText("Cadastrar Coletor");
        jButtonColetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColetorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonColetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, -1));

        cadastraBairro.setText("Cadastrar Bairro");
        cadastraBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraBairroActionPerformed(evt);
            }
        });
        jPanel1.add(cadastraBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 150, -1));

        jButtonSituacaoOperacional.setText("Registrar S.O. da Lixeira");
        jButtonSituacaoOperacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSituacaoOperacionalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSituacaoOperacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 170, -1));

        jButtonColeta.setText("Gerar Rota para Coleta");
        jButtonColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColetaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonColeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, -1));

        jButtonStatus.setText("Criar Status");
        jButtonStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 300));

        setSize(new java.awt.Dimension(524, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonColetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColetorActionPerformed
        // TODO add your handling code here:
        TelaCadastroColetor tCadastroColetor = new TelaCadastroColetor();
        tCadastroColetor.setVisible(true);
    }//GEN-LAST:event_jButtonColetorActionPerformed

    private void cadastraBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraBairroActionPerformed
        // TODO add your handling code here:
        TelaCadastroBairro tCadastroBairro = new TelaCadastroBairro();
        tCadastroBairro.setVisible(true);
    }//GEN-LAST:event_cadastraBairroActionPerformed

    private void jButtonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusActionPerformed
        // TODO add your handling code here:
        TelaCadastroStatus tCadastroStatus = new TelaCadastroStatus();
        tCadastroStatus.setVisible(true);
    }//GEN-LAST:event_jButtonStatusActionPerformed

    private void jButtonLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLixeiraActionPerformed
        // TODO add your handling code here:
        TelaCadastroLixeira tCadastroLixeira = new TelaCadastroLixeira();
        tCadastroLixeira.setVisible(true);
    }//GEN-LAST:event_jButtonLixeiraActionPerformed

    private void jButtonSituacaoOperacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSituacaoOperacionalActionPerformed
        // TODO add your handling code here:
        TelaRegistraSO tSituacaoOperacional = new TelaRegistraSO();
        tSituacaoOperacional.setVisible(true);
    }//GEN-LAST:event_jButtonSituacaoOperacionalActionPerformed

    private void jButtonColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColetaActionPerformed
        // TODO add your handling code here:
        TelaColeta tGeraRota = new TelaColeta();
        tGeraRota.setVisible(true);
    }//GEN-LAST:event_jButtonColetaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastraBairro;
    private javax.swing.JButton jButtonColeta;
    private javax.swing.JButton jButtonColetor;
    private javax.swing.JButton jButtonLixeira;
    private javax.swing.JButton jButtonSituacaoOperacional;
    private javax.swing.JButton jButtonStatus;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
