/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import coletainteligente.Coletor;
import coletainteligente.PersistenciaArquivo;
import coletainteligentedao.ColetorDAO;
import java.util.List;
import validador.ValidadorColetor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thiag
 */
public class TelaCadastroColetor extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form TelaCadastroColetor
     */
    public TelaCadastroColetor() {
        initComponents();
        inicializa();
    }
    private void inicializa() {
        
        //CRIA CABEÇALHO
        model.setColumnIdentifiers(new Object[]{"Cod_coletor","Placa","modelo", "marca", "ano", "capacidade", "latitude", "longitude"});
        //SETANDO TABELA
        jTableColetores.setModel(model);
        listaColetores(); 
        
        ColetorDAO coletordao = new ColetorDAO();
        List listamodelo = coletordao.selectListaModelo();
        jComboBoxModelo.removeAllItems();
        jComboBoxModelo.addItem("Todos");
        for (Object modelo : listamodelo) {
            jComboBoxModelo.addItem(modelo.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFildcod = new javax.swing.JTextField();
        jTextFildmarca = new javax.swing.JTextField();
        jTextFildplaca = new javax.swing.JTextField();
        jTextFildano = new javax.swing.JTextField();
        jButtonRegistrarColetor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFildcapacidade = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableColetores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFildmodelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFildlatitude = new javax.swing.JTextField();
        jTextFildlongitude = new javax.swing.JTextField();
        jComboBoxModelo = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Coletor");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Placa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 5);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 5);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 5);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Ano");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel8, gridBagConstraints);

        jTextFildcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFildcodActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 5);
        jPanel1.add(jTextFildcod, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFildmarca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFildplaca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFildano, gridBagConstraints);

        jButtonRegistrarColetor.setText("Registrar Veículo");
        jButtonRegistrarColetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarColetorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 5);
        jPanel1.add(jButtonRegistrarColetor, gridBagConstraints);

        jLabel9.setText("Capacidade");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 5);
        jPanel1.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 5);
        jPanel1.add(jTextFildcapacidade, gridBagConstraints);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jButtonLimpar, gridBagConstraints);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jButtonSair, gridBagConstraints);

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jButton1, gridBagConstraints);

        jTableColetores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableColetores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableColetoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableColetores);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 656;
        gridBagConstraints.ipady = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Filtrar por modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Código");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jTextFildmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFildmodeloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFildmodelo, gridBagConstraints);

        jLabel3.setText("Latitude");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel10.setText("Longitude");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel10, gridBagConstraints);

        jTextFildlatitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFildlatitudeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFildlatitude, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFildlongitude, gridBagConstraints);

        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxModeloMouseClicked(evt);
            }
        });
        jComboBoxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jComboBoxModelo, gridBagConstraints);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jButtonBuscar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -51;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 54);
        getContentPane().add(jPanel1, gridBagConstraints);

        setSize(new java.awt.Dimension(697, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFildlatitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFildlatitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFildlatitudeActionPerformed

    private void jTextFildmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFildmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFildmodeloActionPerformed

    private void jTableColetoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableColetoresMouseClicked
            selecionaLinha();
    }//GEN-LAST:event_jTableColetoresMouseClicked

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        if (!jTextFildcod.getText().equals("")
            || !jTextFildmarca.getText().equals("")
            || !jTextFildcapacidade.getText().equals("")
            || !jTextFildmodelo.getText().equals("")
            || !jTextFildplaca.getText().equals("")
            || !jTextFildano.getText().equals("")
            || !jTextFildlatitude.getText().equals("")
            || !jTextFildlongitude.getText().equals("")){
            int resposta = JOptionPane.showConfirmDialog(null, "Há campos preenchidos!\nTem certeza que deseja sair dessa tela?");

            if (resposta == JOptionPane.YES_OPTION){
                this.dispose();
            }
        }else{
            this.dispose();
        }
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        jTextFildcod.setText("");
        jTextFildmarca.setText("");
        jTextFildmodelo.setText("");
        jTextFildcapacidade.setText("");
        jTextFildplaca.setText("");
        jTextFildano.setText("");
        jTextFildlatitude.setText("");
        jTextFildlongitude.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonRegistrarColetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarColetorActionPerformed

        Coletor coletor;
        ColetorDAO coletordao = new ColetorDAO();
        ValidadorColetor validaColetor = new ValidadorColetor();
        PersistenciaArquivo registro = new PersistenciaArquivo();
        
        String codigo = jTextFildcod.getText();
        String placa = jTextFildplaca.getText();
        String marca = jTextFildmarca.getText();
        String modelo = jTextFildmodelo.getText();
        String ano = jTextFildano.getText();
        String capacidade = jTextFildcapacidade.getText();
        String latitude = jTextFildlatitude.getText();
        String longitude = jTextFildlongitude.getText();
        

        try {
            coletor = new Coletor();
            coletor.setCodigo(codigo);
            coletor.setPlaca(placa);
            coletor.setMarca(marca);
            coletor.setModelo(modelo);
            coletor.setAno(ano);
            coletor.setLatitude(latitude);
            coletor.setLongitude(longitude);  
            coletor.setCapacidade(capacidade);
            registro.salvaColetor(coletor);
            coletordao.insere(coletor);
            listaColetores();

        } catch (Exception ex){
            Logger.getLogger(TelaCadastroColetor.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButtonRegistrarColetorActionPerformed

    private void jTextFildcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFildcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFildcodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Coletor coletor;
        ColetorDAO coletordao = new ColetorDAO();
        ValidadorColetor validaColetor = new ValidadorColetor();
        
        String codigo = jTextFildcod.getText();
        String placa = jTextFildplaca.getText();
        String marca = jTextFildmarca.getText();
        String modelo = jTextFildmodelo.getText();
        String ano = jTextFildano.getText();
        String capacidade = jTextFildcapacidade.getText();
        String latitude = jTextFildlatitude.getText();
        String longitude = jTextFildlongitude.getText();
        

        try {
            coletor = new Coletor();
            coletor.setCodigo(codigo);
            coletor.setPlaca(placa);
            coletor.setMarca(marca);
            coletor.setModelo(modelo);
            coletor.setAno(ano);
            coletor.setLatitude(latitude);
            coletor.setLongitude(longitude);  
            coletor.setCapacidade(capacidade);
            coletordao.deleta(coletor);
            listaColetores();

        } catch (Exception ex){
            Logger.getLogger(TelaCadastroColetor.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeloActionPerformed

    }//GEN-LAST:event_jComboBoxModeloActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(jComboBoxModelo.getSelectedItem().toString().equalsIgnoreCase("Todos")){
            listaColetores();  
       }else {
            filtra();
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBoxModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxModeloMouseClicked

    }//GEN-LAST:event_jComboBoxModeloMouseClicked
    public void listaColetores() {
        
        while (model.getRowCount() > 0)
        {
         model.removeRow(0);
        }
        
        ColetorDAO coletordao = new ColetorDAO();
        coletordao.listaColetores(model);
        jTableColetores.setModel(model);
        jScrollPane1.setViewportView(jTableColetores);
    }
    public void filtra() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        
        ColetorDAO coletordao = new ColetorDAO();
        String modelo = jComboBoxModelo.getSelectedItem().toString();
        coletordao.filtraColetoresPorMarca(model,modelo);
        jTableColetores.setModel(model);
        jScrollPane1.setViewportView(jTableColetores);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroColetor().setVisible(true);
            }
        });
    }
    
    public void selecionaLinha() {
        int select = jTableColetores.getSelectedRow();
        jTextFildcod.setText(jTableColetores.getModel().getValueAt(select,0).toString());
        jTextFildplaca.setText(jTableColetores.getModel().getValueAt(select,1).toString());
        jTextFildmodelo.setText(jTableColetores.getModel().getValueAt(select,2).toString());
        jTextFildmarca.setText(jTableColetores.getModel().getValueAt(select,3).toString());
        jTextFildano.setText(jTableColetores.getModel().getValueAt(select,4).toString());
        jTextFildcapacidade.setText(jTableColetores.getModel().getValueAt(select,5).toString());
        jTextFildlatitude.setText(jTableColetores.getModel().getValueAt(select,6).toString());
        jTextFildlongitude.setText(jTableColetores.getModel().getValueAt(select,7).toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonRegistrarColetor;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableColetores;
    private javax.swing.JTextField jTextFildano;
    private javax.swing.JTextField jTextFildcapacidade;
    private javax.swing.JTextField jTextFildcod;
    private javax.swing.JTextField jTextFildlatitude;
    private javax.swing.JTextField jTextFildlongitude;
    private javax.swing.JTextField jTextFildmarca;
    private javax.swing.JTextField jTextFildmodelo;
    private javax.swing.JTextField jTextFildplaca;
    // End of variables declaration//GEN-END:variables
}
