/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import coletaInteligente.Descarte;
import coletaInteligente.Cidadao;
import coletaInteligente.PersistenciaArquivo;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author thiag
 */
public class TelaPrincipalCidadao extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalCidadao
     */
    public TelaPrincipalCidadao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLatitude = new javax.swing.JTextField();
        jTextFieldLongitude = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonLocalizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldDistancia = new javax.swing.JTextField();
        jTextFieldDirecao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cidadão");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 34, -1, -1));

        jLabel2.setText("Lixeira Inteligênte Vazia mais Próxima");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 79, -1, -1));
        getContentPane().add(jTextFieldLatitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 111, 95, -1));
        getContentPane().add(jTextFieldLongitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 149, 95, -1));

        jLabel3.setText("Latitude");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 114, -1, -1));

        jLabel4.setText("Longitude");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 152, -1, -1));

        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 187, -1, -1));

        jButton1.setText("Registrar Descarte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 259, -1, -1));
        getContentPane().add(jTextFieldDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 221, 96, -1));
        getContentPane().add(jTextFieldDirecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 221, 90, -1));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
        // TODO add your handling code here:
        //ESTA PARTE NÃO ESTÁ ACRESCENTANDO NADA AO SISTEMA POR ENQUANTO
        //DEVERIA BUSCAR A LOCALIZAÇÃO DE UMA LIXEIRA NO ARQUIVO, MAS TÔ COM PREGUIÇA
        Random random = new Random();
        int direcao;
        
        jTextFieldLatitude.setText(String.valueOf(random.nextFloat()));
        jTextFieldLongitude.setText(String.valueOf(random.nextFloat()));
        jTextFieldDistancia.setText(String.valueOf(random.nextInt(10)) + " Minutos");
        
        direcao = random.nextInt(2);
        
        if(direcao == 0)
        {
            jTextFieldDirecao.setText("Go Right");
        }else
        {
            jTextFieldDirecao.setText("Go Left");
        }
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //MAIS UMA VEZ ERA PRA ESTAR BUSCANDO AS INFORMAÇÕES DO ARQUIVO OU BD, MAS A PREGUIÇA FEZ ASSIM
        
        Random random = new Random();
        
        int codLixeira = random.nextInt(100);
        int codCidadao = random.nextInt(100);
        int nivel = random.nextInt(100);
        Calendar data = Calendar.getInstance();
        
        Descarte descarte = new Descarte(codLixeira, codCidadao, nivel, data);
        
        PersistenciaArquivo registro = new PersistenciaArquivo();
        registro.salvaDescarte(descarte);
        
        JOptionPane.showMessageDialog(null, "Descarte Registrado");
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalCidadao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldDirecao;
    private javax.swing.JTextField jTextFieldDistancia;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    // End of variables declaration//GEN-END:variables
}
