/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.admin;


import coletainteligente.Coleta;
import coletainteligente.Coletor;
import coletainteligente.Lixeira;
import coletainteligente.PersistenciaArquivo;
import coletainteligentedao.BairroDAO;
import coletainteligentedao.ColetaDAO;
import coletainteligentedao.ColetorDAO;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thiag
 */
public class TelaCadastroColeta extends javax.swing.JFrame {

    /**
     * Creates new form TelaGeraRota
     */
    private List <Object> listaBairro;
    private List <Coletor> listaColetor;
    public  DefaultTableModel model;
    
    public TelaCadastroColeta() {
        initComponents();
        
        BairroDAO bairrodao = new BairroDAO();
        listaBairro = bairrodao.selectListaBairro();
        
        ColetorDAO coletordao = new ColetorDAO();
        listaColetor = coletordao.listaColetoresList();
        
        jComboBoxBairro.removeAllItems();
        jComboBoxColetor.removeAllItems();
        
        for(Object bairro : listaBairro){
           jComboBoxBairro.addItem((String) bairro);
        }
        
        for(Coletor coletor : listaColetor){
          jComboBoxColetor.addItem(coletor.getPlaca());
        }
        
        //CRIA TABELA
        model = new DefaultTableModel();
        //CRIA CABEÇALHO
        model.setColumnIdentifiers(new Object[]{"Código Lixeira", "Volume Atual", "Latitude", "Longitude"});
        //SETANDO TABELA
        jTable1.setModel(model);
        jScrollPane2.setViewportView(jTable1); 
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlColetor = new javax.swing.JLabel();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jButtonGerarRota = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonIniciarColeta = new javax.swing.JButton();
        jlNivelColetado = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxColetor = new javax.swing.JComboBox();
        jlBairro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerar Rota");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlColetor.setText("Selecione o coletor");
        getContentPane().add(jlColetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 4, -1, 20));

        getContentPane().add(jComboBoxBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 380, -1));

        jButtonGerarRota.setText("Gerar Rota");
        jButtonGerarRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRotaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGerarRota, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jButtonIniciarColeta.setText("Iniciar Coleta");
        jButtonIniciarColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarColetaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciarColeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jlNivelColetado.setText("Volume Coletado");
        getContentPane().add(jlNivelColetado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, 20));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 70, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 380, 120));

        jComboBoxColetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxColetor.setSelectedIndex(-1);
        jComboBoxColetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColetorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxColetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 380, -1));

        jlBairro.setText("Selecione a bairro");
        getContentPane().add(jlBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        setSize(new java.awt.Dimension(558, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonGerarRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRotaActionPerformed
        
        BairroDAO bairrodao = new BairroDAO();
        jTextFieldTotal.setText("");
        if(jComboBoxBairro.getSelectedIndex() != -1  && jComboBoxColetor.getSelectedIndex() != -1)
        {
            
            String nomeBairro = (String) listaBairro.get(jComboBoxBairro.getSelectedIndex());
            float capacidadeCaminhao = (float) listaColetor.get(jComboBoxColetor.getSelectedIndex()).getCapacidade();
            // REMOVE LINHA DAS TABELAS
            while (model.getRowCount() > 0)
            {
             model.removeRow(0);
            }//

            bairrodao.listaLixeirasCheias(model, nomeBairro,capacidadeCaminhao);

            if (model.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Não há lixeiras cheias!");
            }
            
            jTable1.setModel(model);
            jScrollPane2.setViewportView(jTable1); 
            
        }else{
             JOptionPane.showMessageDialog(null, "Deve ser selecionado um bairro e um coletor!");
        }
    }//GEN-LAST:event_jButtonGerarRotaActionPerformed

    private void jButtonIniciarColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarColetaActionPerformed
        
        if(model.getRowCount() != 0){
            int indice = jComboBoxColetor.getSelectedIndex();
            Coletor coletor =  listaColetor.get(indice);
            Lixeira lixeira = new Lixeira();
            Coleta coleta = new Coleta();


            float nivelTotal = 0;

            while (model.getRowCount() > 0 )
            {
                try {
                    // Pega primeira linha da tabela
                    lixeira.setCodigo(jTable1.getModel().getValueAt(0,0).toString());
                    coleta.setVolume(jTable1.getModel().getValueAt(0,1).toString());
                } catch (Exception ex) {
                    Logger.getLogger(TelaCadastroColeta.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Remove primeira linha
                model.removeRow(0);

                //JOptionPane.showMessageDialog(null, "Lixeira coletada:  "+ lixeira.getCodigo());

                coleta.setColetor(coletor);
                coleta.setLixeira(lixeira);
                coleta.setData(Calendar.getInstance().getTime());

                ColetaDAO coletadao = new ColetaDAO();
                coletadao.insere(coleta);
                PersistenciaArquivo arquivo = new PersistenciaArquivo();
                arquivo.salvaColeta(coleta);

                nivelTotal += coleta.getVolume();
                jTextFieldTotal.setText(Float.toString(nivelTotal));

               try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaCadastroColeta.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            // SET do model
            jTable1.setModel(model);
            jScrollPane2.setViewportView(jTable1);

            JOptionPane.showMessageDialog(null, "Coleta Registrada");
            
        }
        
    }//GEN-LAST:event_jButtonIniciarColetaActionPerformed

    private void jComboBoxColetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxColetorActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroColeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarRota;
    private javax.swing.JButton jButtonIniciarColeta;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxBairro;
    private javax.swing.JComboBox jComboBoxColetor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlColetor;
    private javax.swing.JLabel jlNivelColetado;
    // End of variables declaration//GEN-END:variables
}
