/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.admin;

import visao.admin.TelaCadastroSO;
import visao.admin.TelaCadastroColeta;
import visao.admin.TelaCadastroStatus;
import visao.admin.TelaCadastroLixeira;
import visao.admin.TelaCadastroColetor;
import visao.admin.TelaCadastroBairro;

/**
 *
 * @author thiag
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalAdm
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrarLixeira = new javax.swing.JButton();
        jButtonColetor = new javax.swing.JButton();
        jButtonCadastraBairro = new javax.swing.JButton();
        jButtonRegistrarSituacaoOperacionalLixeira = new javax.swing.JButton();
        jButtonGerarRotaColeta = new javax.swing.JButton();
        jButtonCriarStatus = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jButtonCadastrarLixeira.setText("Cadastrar Lixeira");
        jButtonCadastrarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarLixeiraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 4, 0, 40);
        jPanel1.add(jButtonCadastrarLixeira, gridBagConstraints);

        jButtonColetor.setText("Cadastrar Coletor");
        jButtonColetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColetorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 40, 0, 0);
        jPanel1.add(jButtonColetor, gridBagConstraints);

        jButtonCadastraBairro.setText("Cadastrar Bairro");
        jButtonCadastraBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraBairroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 40, 0, 0);
        jPanel1.add(jButtonCadastraBairro, gridBagConstraints);

        jButtonRegistrarSituacaoOperacionalLixeira.setText("Registrar S.O. da Lixeira");
        jButtonRegistrarSituacaoOperacionalLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarSituacaoOperacionalLixeiraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 40);
        jPanel1.add(jButtonRegistrarSituacaoOperacionalLixeira, gridBagConstraints);

        jButtonGerarRotaColeta.setText("Gerar Rota para Coleta");
        jButtonGerarRotaColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRotaColetaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 40);
        jPanel1.add(jButtonGerarRotaColeta, gridBagConstraints);

        jButtonCriarStatus.setText("Criar Status");
        jButtonCriarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarStatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 40, 0, 0);
        jPanel1.add(jButtonCriarStatus, gridBagConstraints);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 17, 0);
        jPanel1.add(jButtonVoltar, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        setSize(new java.awt.Dimension(559, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonColetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColetorActionPerformed
        // TODO add your handling code here:
        TelaCadastroColetor tCadastroColetor = new TelaCadastroColetor();
        tCadastroColetor.setVisible(true);
    }//GEN-LAST:event_jButtonColetorActionPerformed

    private void jButtonCadastraBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraBairroActionPerformed
        // TODO add your handling code here:
        TelaCadastroBairro tCadastroBairro = new TelaCadastroBairro();
        tCadastroBairro.setVisible(true);
    }//GEN-LAST:event_jButtonCadastraBairroActionPerformed

    private void jButtonCriarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarStatusActionPerformed
        // TODO add your handling code here:
        TelaCadastroStatus tCadastroStatus = new TelaCadastroStatus();
        tCadastroStatus.setVisible(true);
    }//GEN-LAST:event_jButtonCriarStatusActionPerformed

    private void jButtonCadastrarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarLixeiraActionPerformed
        // TODO add your handling code here:
        TelaCadastroLixeira tCadastroLixeira = new TelaCadastroLixeira();
        tCadastroLixeira.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarLixeiraActionPerformed

    private void jButtonRegistrarSituacaoOperacionalLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarSituacaoOperacionalLixeiraActionPerformed
        // TODO add your handling code here:
        TelaCadastroSO tSituacaoOperacional = new TelaCadastroSO();
        tSituacaoOperacional.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarSituacaoOperacionalLixeiraActionPerformed

    private void jButtonGerarRotaColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRotaColetaActionPerformed
        // TODO add your handling code here:
        TelaCadastroColeta tGeraRota = new TelaCadastroColeta();
        tGeraRota.setVisible(true);
    }//GEN-LAST:event_jButtonGerarRotaColetaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastraBairro;
    private javax.swing.JButton jButtonCadastrarLixeira;
    private javax.swing.JButton jButtonColetor;
    private javax.swing.JButton jButtonCriarStatus;
    private javax.swing.JButton jButtonGerarRotaColeta;
    private javax.swing.JButton jButtonRegistrarSituacaoOperacionalLixeira;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
